### PR TITLE
Tk/dynamic crashlytics

### PR DESCRIPTION
**Pull request by TadeasKriz**
I've replaced direct usage of Firebase Crashlytics ObjC classes with dynamic calls. This way stripped symbols are no longer a problem. The one symbol we still need to mark as "unresolved" (`_FIRCLSExceptionRecordNSException`) is available even after symbols are stripped. That means dyld is able to link it in runtime.

I've also made it into a weak symbol to improve the error message when we try to use it, but it's not available.

### CODE REVIEW

**Comment by JackHurst0** [comment]
Hello @TadeasKriz thanks for this fix!

Do you know if there is a timeline on when we could expect this to be merged and fixed?

**Comment by kpgalligan** [comment]
Sorry all. Review was on me and I've been super busy. Diving in...

**Review by kpgalligan — APPROVED** [review]
👍

**Comment by JackHurst0** [comment]
Thanks once again for this fix @TadeasKriz

Just like @tamimattafi said, if you need real projects to test a pre-release, I can try to make some time to help with that.

**Pull request merged**
